// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRYBwIojhAZB_SNTzejAlfnjvtwB72P-Y',
    appId: '1:166669397200:web:f574f3ff02e35e65eac2d5',
    messagingSenderId: '166669397200',
    projectId: 'deneme3ogrenci',
    authDomain: 'deneme3ogrenci.firebaseapp.com',
    storageBucket: 'deneme3ogrenci.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzyagpN52gKWj5X9EsOyeXGnB3Rpkmcy8',
    appId: '1:166669397200:android:0cdbbcf6a166835ceac2d5',
    messagingSenderId: '166669397200',
    projectId: 'deneme3ogrenci',
    storageBucket: 'deneme3ogrenci.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh5CxXoBwZTi7zHRJvNG-zKJ-OstWHwQ8',
    appId: '1:166669397200:ios:600372b4553e7bbeeac2d5',
    messagingSenderId: '166669397200',
    projectId: 'deneme3ogrenci',
    storageBucket: 'deneme3ogrenci.firebasestorage.app',
    iosBundleId: 'com.example.deneme3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh5CxXoBwZTi7zHRJvNG-zKJ-OstWHwQ8',
    appId: '1:166669397200:ios:600372b4553e7bbeeac2d5',
    messagingSenderId: '166669397200',
    projectId: 'deneme3ogrenci',
    storageBucket: 'deneme3ogrenci.firebasestorage.app',
    iosBundleId: 'com.example.deneme3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRYBwIojhAZB_SNTzejAlfnjvtwB72P-Y',
    appId: '1:166669397200:web:283eacb1fd26504aeac2d5',
    messagingSenderId: '166669397200',
    projectId: 'deneme3ogrenci',
    authDomain: 'deneme3ogrenci.firebaseapp.com',
    storageBucket: 'deneme3ogrenci.firebasestorage.app',
  );
}
